### ISSUE TITLE
Invalid and Insecure Header

### ISSUE THREAD

**Issue by kpirnie** [jazir555/NGINX-8G-Firewall#1]
**Remove**: `add_header X-XSS-Protection "1; mode=block" always;`

**Why**?
The header is non-standard and allows more issues than it protected against.  It is also not supported in the latest browser versions over the last few years.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

_Warning: Even though this feature can protect users of older web browsers that don't yet support [CSP](https://developer.mozilla.org/en-US/docs/Glossary/CSP), in some cases, XSS protection can create XSS vulnerabilities in otherwise safe websites. See the section below for more information._

**Comment by jazir555** [comment]
Removed!
